import type { Metadata } from "next";
import React from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "@/styles/globals.css";
import { DashboardSideBar } from "@/components/layouts/Sidebar/Sidebar";
import Header from "@/components/layouts/Header";
import AuthHeder from "@/components/auth/Layouts/Header";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });
const auth:boolean = false;

export const metadata: Metadata = {
  title: "Nişantaşı Üinversitesi - Bilgi Yönetim Sistemi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" translate="no" suppressHydrationWarning>
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen ${auth ? 'bg-gray-100' : ''}`}>
        <ThemeProvider attribute="class" defaultTheme="light" disableTransitionOnChange>
          {auth ? (
            <>
              <Header />
              <DashboardSideBar />
            </>
          ) : (
            <AuthHeder />
          )}
          <main className={`${auth ? 'md:ml-64 mt-10' : ''}`}>{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
